# docker-compose up ==> start the containers defined in `compose.yml`
# docker-compose down ==> stop and removes the containers
# docker-compose build ==> re/build services defined. Often used when changing Dockerfile or dependencies
# docker-compose pull ==> pull latest version of the images defined in `compose.yml` from Docker Registry
# docker-compose logs ==> Show logs for services. Adding '-f' will follow the logs in realtime.

services:
    backend:
        build:
            context: .
        ports:
            - '3101:3000'
        depends_on:
            - db

    db:
        image: postgres:16
        ports:
            - '5432:5432'
        env_file:
            - path: .env
              required: true
        # environment:
        #     POSTGRES_USER: ${POSTGRES_USER}
        #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        #     POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            # Volumes tags are used to persist data between container restarts
            # Syntax follows as <folder path on local machine>:<folder path to retrieve on container>
            - ${PWD}/db-data/:/var/lib/postgresql/data/

            # # Volumes tags also used to add a postgres initialization script
            # - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    db-data:
